AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFront Distribution for S3 Static Website Hosting

Parameters:
  BucketName:
    Type: String
    Description: Name of the existing S3 bucket with static website hosting enabled

Resources:
  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Access Identity for CloudFront to access S3 bucket

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html

        Origins:
          - Id: S3Origin
            DomainName: !Sub "${BucketName}.s3-website-${AWS::Region}.amazonaws.com"
            CustomOriginConfig:
              OriginProtocolPolicy: http-only

        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none

        CustomErrorResponses:
          - ErrorCode: 404
            ResponsePagePath: /index.html
            ResponseCode: 200
            ErrorCachingMinTTL: 0

        ViewerCertificate:
          CloudFrontDefaultCertificate: true
          # ACMCertificateArn: arn:aws:acm:us-east-1:123456789012:certificate/xxxxxx
          # SslSupportMethod: sni-only

        Comment: "CloudFront distribution for static website"
        PriceClass: PriceClass_100
        HttpVersion: http2

Outputs:
  DistributionDomainName:
    Description: CloudFront distribution domain name
    Value: !GetAtt CloudFrontDistribution.DomainName
